### PR TITLE
Fix recipe sorter, ore dictionary support

### LINKED ISSUE #290: Register PresentRecipe in RecipeSorter

### PR DESCRIPTION
**Pull request by Adaptivity**
Chests and crafting tabels were registered to have better compatibility with ganymedes01's WoodStuff mod. Also, closes #290

@copygirl Can you pull two my PRs and make a new release?

### CODE REVIEW

**Comment by copygirl** [comment]
I don't have anything set up to even build it, and I've given up responsibility. I'll leave it up to @Victorious3 and friends. Unless you want to go ahead and maintain it, feel free to release your fork to the public.

**Comment by Adaptivity** [comment]
Maybe @Victorious3 can merge this too and make a new release then? I would appreciate this.

**Comment by Adaptivity** [comment]
Oh, this should be used for reinforced chests... but I don't really know how to change chest recipes. Maybe you can leave this here, so maybe someone will add support for actual recipes later?

**Comment by copygirl** [comment]
I guess what should be done is checking the ore dictionary for whether the entry exists, and if not, just use chests instead. Might not work if mods add ore dictionary entries after BS registers their recipes though.

**Comment by Adaptivity** [comment]
No reason to do checking. Better to register it, I've added support for a few mods (Buildcraft and Ender IO, as I remember) and it's working great.

**Pull request closed without merging**
