### PR TITLE
Create sk_SK.lang

### PR DESCRIPTION
**Pull request by leSamo**
Partial translation of BetterStorage... I will complete it once I have my new keyboard.

### CODE REVIEW

**Comment by copygirl** [comment]
Thanks! Do you mind if I wait until the translation is finished?

Keeping "BetterStorage" as-is is probably the right thing to do.

**Comment by copygirl** [comment]
FYI you didn't need to close the PR, just put the rest of the changes into another commit and push it to your patch-1 and it will automatically update.

**Comment by leSamo** [comment]
Oh, thanks I still don't really know how do these pull requests work.

**Comment by leSamo** [comment]
And I suppose # is line break or not?

**Comment by copygirl** [comment]
Yeah, except for in the Thaumcraft entry description

**Comment by leSamo** [comment]
There you go. Done.

**Pull request merged**
